name: Deploy Project
on: 
  push:
    branches: 
    - 'main'
    - 'master'
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3
      with: 
        repository: '${{ github.repository }}'
        ref: 'master'
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build Project
      run: npm run build
    - name: Deploy
      run: echo "Deploying..."
